// src/app/layout.js
import '../../public/css/bootstrap.min.css';
import '../../public/css/fontawesome.css';
import '../../public/css/animate.min.css';
import '../../public/css/swiper-bundle.min.css';
import '../../public/css/magnific-popup.min.css';
import '../../public/css/odometer.min.css';
import '../../public/css/style.css';
// import '../../public/css/style.css';
import Footer from './components/Footer';
import MyScript from './components/MyScript';

import Link from 'next/link';
import Preloader from './components/Preloader';
import Heads from './components/Heads';

import { SpeedInsights } from '@vercel/speed-insights/next';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  charset: 'utf-8',
  keywords: 'Bootstrap Site Template',
  author: 'Webrock',
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <div className="backtotop">
            <Link href="#" className="scroll">
              <i className="fa-solid fa-arrow-up"></i>
            </Link>
        </div>
        {/* <Preloader /> */}
        <Heads />
        <main>
          { children }
          <SpeedInsights />
        </main>

      <Footer />
      </body>

    <MyScript />
    </html>
  )
}